# SVD Example in Python

## Python SVD Basics

In [1]:
import numpy as np
from numpy import ndarray

View the documentation on the numpy linear algebra [here](https://docs.scipy.org/doc/numpy-1.16.1/reference/routines.linalg.html).

First let's define a matrix:

In [2]:
A = np.matrix('1 2 3; 4 5 6')
print (A)

[[1 2 3]
 [4 5 6]]


Next let's perform the SVD on that matrix:

In [3]:
U, S, V = np.linalg.svd(A, full_matrices = True)
print('U = \n', U, '\n\nS = \n', S, '\n\nV = \n', V)

U = 
 [[-0.3863177  -0.92236578]
 [-0.92236578  0.3863177 ]] 

S = 
 [9.508032   0.77286964] 

V = 
 [[-0.42866713 -0.56630692 -0.7039467 ]
 [ 0.80596391  0.11238241 -0.58119908]
 [ 0.40824829 -0.81649658  0.40824829]]


Let's do the same thing but make S a diagonal matrix.
This is because numpy just gives the singular values without placing the zeros.

In [4]:
U, S, V = np.linalg.svd(A, full_matrices = True)
S = np.diag(S)
print('U = \n', U, '\n\nS = \n', S, '\n\nV = \n', V)

U = 
 [[-0.3863177  -0.92236578]
 [-0.92236578  0.3863177 ]] 

S = 
 [[9.508032   0.        ]
 [0.         0.77286964]] 

V = 
 [[-0.42866713 -0.56630692 -0.7039467 ]
 [ 0.80596391  0.11238241 -0.58119908]
 [ 0.40824829 -0.81649658  0.40824829]]


Oops, S is not the right size still, we need S to have one more column of zeros:

In [5]:
S_dim = S.shape # create a tuple of the dimensions
S_new = np.zeros((S_dim[0], S_dim[1]+1)) # matrix of zeros one more column than S
print(S_new)

S_new[:,:-1] = S
print('\nU = \n', U, '\n\nS_new = \n', S_new, '\n\nV = \n', V)

[[0. 0. 0.]
 [0. 0. 0.]]

U = 
 [[-0.3863177  -0.92236578]
 [-0.92236578  0.3863177 ]] 

S_new = 
 [[9.508032   0.         0.        ]
 [0.         0.77286964 0.        ]] 

V = 
 [[-0.42866713 -0.56630692 -0.7039467 ]
 [ 0.80596391  0.11238241 -0.58119908]
 [ 0.40824829 -0.81649658  0.40824829]]


Much better.

Now, let's verify that we can reconstruct A with these three matrices.


In [6]:
U @ S_new @ V

matrix([[1., 2., 3.],
        [4., 5., 6.]])

Sweet! Now time for SVD on an image.

## Python SVD on Image - Challenge

First let's load in the cat image:

In [1]:
import imageio
from PIL import Image
import matplotlib.pyplot as plt # matlab like plotting functions

img = Image.open('cat.jpg')
plt.imshow(img, cmap=plt.cm.gray)
plt.show()

<Figure size 640x480 with 1 Axes>

Next, let's convert the image to a matrix:

In [8]:
img_m = np.asarray(img, dtype="int32")
print(img_m)

[[159 159 158 ... 188 188 188]
 [159 159 158 ... 188 188 188]
 [159 158 158 ... 189 189 189]
 ...
 [167 167 167 ...  13  12  11]
 [166 165 163 ...  17  15  13]
 [166 165 163 ...  17  15  13]]


Now let's perform the SVD on that image.

In [9]:
U, S, V = np.linalg.svd(img_m, full_matrices = True)

Just like we did earlier, let's make S a diagonal matrix (since right now it is just a one dimensional list of eigenvectors)

In [10]:
S = np.diag(S)

In [11]:
u_size = np.shape(U)
s_size = np.shape(S)
v_size = np.shape(V)
print('U is:', u_size, '\nS is:',s_size, '\nV is:', v_size)

U is: (706, 706) 
S is: (480, 480) 
V is: (480, 480)


To multiply these together, we need S to be (706, 480). The command below adds zeros to make the matrix S have the correct dimensions.

In [12]:
S_new = np.zeros((706, 480))
S_new[:480, :480] = S
print(S_new)

[[72919.00887597     0.             0.         ...     0.
      0.             0.        ]
 [    0.         22505.48063871     0.         ...     0.
      0.             0.        ]
 [    0.             0.         13432.06665438 ...     0.
      0.             0.        ]
 ...
 [    0.             0.             0.         ...     0.
      0.             0.        ]
 [    0.             0.             0.         ...     0.
      0.             0.        ]
 [    0.             0.             0.         ...     0.
      0.             0.        ]]


Now let's verify that our breakdown is equivalent to the original matrix.

In [13]:
a = U @ S_new @ V

In [14]:
np.isclose(a, img_m)

array([[ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       ...,
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True]])